title: "The Hedonist's Holistic Guide to Vintage Shaving"
description: "A vintage shaving workshop for the hedonistic gentleperson"
url: "https://github.com/siawyoung/immaculate"
paginate:	5 # The number of posts to show per page on your homepage
name: "Florian 'bobschi' Holzner and Michael 'Schatz' Kellner"
markdown: kramdown
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
